### ISSUE TITLE
running oemof_installation_test on venv

### ISSUE THREAD

**Issue by nehadimri1991** [oemof/oemof-solph#1084]
I'm getting the following error message when running oemof_installation_test command from inside the virtual environment.

Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "C:\Daten\solph\venv\Scripts\oemof_installation_test.exe\__main__.py", line 4, in <module>
ModuleNotFoundError: No module named 'oemof.solph.console_scripts'

**Comment by fwitte** [comment]
@nehadimri1991, can you post the version of `oemof-solph` installed on your machine?

**Comment by nehadimri1991** [comment]
@fwitte It's version 0.5.0

**Comment by p-snft** [comment]
In v0.5.0, the script was missing. It is re-added in [v0.5.1](https://github.com/oemof/oemof-solph/releases/tag/v0.5.1). Can you confirm that it works with an updated version?

**Comment by nehadimri1991** [comment]
It works with v0.5.1. Although there are two warning messages.

![image](https://github.com/oemof/oemof-solph/assets/83694401/2465f455-0840-42cd-a1a3-ed5352885d14)

**Comment by fwitte** [comment]
The first warning has already been dealt with in #1049 and will be available with the upcoming release #1083, the other one I do not know right now. I cannot reproduce it with the current dev version, but it might be related to the `numpy` 2.0 release, which broke `pyomo` in some parts. Can you post your `numpy` version here?

**Comment by nehadimri1991** [comment]
My numpy version is 1.26.4. Here is a list of all the packages installed in this virtual environment.
[venv_packages.txt](https://github.com/user-attachments/files/15926671/venv_packages.txt)
